Feat: Refactor: delete commit function
Changes to be committed:
modified:   .scripts/bk-files

diff --git a/.scripts/bk-files b/.scripts/bk-files
--- a/.scripts/bk-files
+++ b/.scripts/bk-files
@@ -1,20 +1,15 @@
 #!/bin/bash
 
-commit_and_push() {
-    local directory=$1
-    local message=$2
-
-    cd "$directory" || { echo "ERROR"; exit; }
-    git add .
-    git commit -m "$message"
-    git push origin main
-}
-
-paths=("/home/adrs/vimwiki/personal" "/home/adrs/.task/")
+paths=(
+    "/home/adrs/vimwiki/personal"
+    "/home/adrs/.task/"
+)
 cdate=$(date +'%Y-%m-%d %H:%M:%S')
 
 for path in "${paths[@]}"
 do
-    commit_and_push "$path" "Feat: Update $cdate"
+    cd "$path" || { echo "ERROR"; exit; }
+    git add .
+    git commit -m "Feat: Update $cdate"
+    git push origin main
 done
-
